#include<iostream.h>
#include<conio.h>

void main()
{
	int i;
	int original[100],no;
		cout<<"enter total ellements in array";
		cin>>no;
		for(i=0;i<no;i++)
		{
			cin>>original[i];
		}
		if(no%2==1)
		{
		void swap();
		}
	void swap()
	{
	int temp;
	temp=original[start];
	original[start]=original[end];
	original[end]=temp;
	start++;
	end--;
	void printarray();
	}
	void printarray()
	{
		for(i=0;i<no;i++)
		{
		cout<<original[i];
		}
	}
}
