/*#include<iostream.h>
#include<conio.h>
void main()
{
clrscr();
int b,p,i,pow=1;
clrscr();
cout<<"enter base and power:";
cin>>b>>p;
for(i=p;i>0;i--)
{
pow=pow*b;
}
cout<<"power is:"<<pow;
getch();
} */
/* #include<stdio.h>
 #include<conio.h>
 void main()
{
 int a,b,c;
 clrscr();
 printf("\n enter the value of a and b");
 scanf("%d",&a);
 scanf("%d",&b);
 c=a+b;
 printf("\n\t the value of c is %d ");
 getch();
}*/

#include<iostream.h>
#include<conio.h>
void main()
{
 int a,b,c;
 clrscr();
 cout<<"\n\t enter the value of a and b";
 cin>>a>>b;
 c=a+b;
 cout<<"\n\t\t the value of c is "<<c;
 getch();
}










